name: modelo_app_flutter_20251
description: "Aplicação de exemplo de Arquitetura"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  routefly: ^3.1.3
  provider: ^6.1.5
  signals: ^6.0.2
  openapi_generator_annotations: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  openapi_generator: ^6.1.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

